import type { Metadata, Viewport } from "next";
import { Cormorant_SC, Nunito } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { southland } from "@/lib/fonts";
import { Button } from "@/components/ui/button";
import { MenuIcon } from "lucide-react";
import Image from "next/image";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import Link from "next/link";
import { NavBar } from "./_components/navbar";
import { Toaster } from "sonner";

const cormorant = Cormorant_SC({ weight: ["300", "400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className={cn(cormorant.className, "font-light bg-beige min-h-screen flex flex-col")}>
        <NavBar />
        <main className="flex-grow">
          {children}
        </main>
        <Toaster />
        <footer className="w-full flex flex-col">
          <div>
            <div className="aspect-video relative flex items-center justify-center max-h-72 w-full bottom-0">
              <div className="relative w-full h-full">
                <Image
                  src="/images/flowers.png"
                  className="object-contain"
                  fill
                  alt="flowers"
                />
              </div>
              <div className="relative hidden md:flex w-full h-full">
                <Image
                  src="/images/flowers.png"
                  className="object-contain"
                  fill
                  alt="flowers"
                />
              </div>
              <div className="relative hidden lg:flex w-full h-full">
                <Image
                  src="/images/flowers.png"
                  className="object-contain"
                  fill
                  alt="flowers"
                />
              </div>
              <div className="relative hidden xl:flex w-full h-full">
                <Image
                  src="/images/flowers.png"
                  className="object-contain"
                  fill
                  alt="flowers"
                />
              </div>
              <div className="relative hidden 2xl:flex w-full h-full">
                <Image
                  src="/images/flowers.png"
                  className="object-contain"
                  fill
                  alt="flowers"
                />
              </div>
            </div>
          </div>
          {/* <div className="w-full">
            <div className="flex gap-x-1 italic">
              <span className="text-xs">Utvecklad & Tillhandahållen av</span>
              <span className="text-xs font-semibold">NOLL2 SOLUTIONS AB</span>
            </div>
          </div> */}
        </footer>
      </body>
    </html>
  );
}
