import type { Metadata, Viewport } from "next";
import { Cormorant, Nunito } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { southland } from "@/lib/fonts";
import { Button } from "@/components/ui/button";
import { MenuIcon } from "lucide-react";
import Image from "next/image";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import Link from "next/link";
import { NavBar } from "./_components/navbar";
import { Toaster } from "sonner";

const cormorant = Cormorant({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv">
      <body className={cn(cormorant.className, "bg-beige min-h-screen flex flex-col")}>
        <NavBar />
        <main className="flex-grow">
          {children}
        </main>
        <Toaster />
        <footer className="w-full">
          <div className="aspect-video relative flex items-center justify-center">
            <Image src="/images/flowers.png" className="object-cover" fill alt="flowers" />
          </div>
          <div className="relative w-full mx-auto">
            <div className="absolute bottom-1">
              <div className="flex flex-col items-center backdrop-blur-md rounded-lg p-2">
                <span className="text-xs">Utvecklad & Tillhandahållen av</span>
                <span className="text-xs">NOLL2 SOLUTIONS AB</span>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
